### ISSUE TITLE
num_terms (and likely num_comp) throw error in training when doubles supplied instead of integers.

### ISSUE THREAD

**Issue by yogat3ch** [tidymodels/dials#132]
Hi folks,
I think this is an easy bug to fix. 

I kept encountering the note:
 `internal: Error: Must subset elements with a valid subscript vector.\n\033[31mx\033[39m Can't convert from <double> to <integer> due to loss of precision.`
while training with `tune_grid`.

It appears to be related to `dials::num_terms` demonstrated in the reprex below:

```
.dt <-
  data.frame(
    y = rnorm(20),
    x = rnorm(20),
    time = seq(
      from = lubridate::today() - 19,
      to = lubridate::today(),
      by = "day"
    )
  )



rec <- recipes::recipe(y ~ ., data = .dt)

.roll <- rsample::rolling_origin(
  .dt,
  initial = 5,
  skip = 5,
  cumulative = TRUE
)

par_mars = dials::parameters(
  list(
    num_terms = dials::num_terms(c(1,1)),
    prod_degree = dials::prod_degree(),
    prune_method = dials::prune_method(dials::values_prune_method[!dials::values_prune_method %in% c("backward", "cv", "exhaustive", "none")])
  )
)

mod_mars = parsnip::mars(
  mode = "regression",
  num_terms = tune::tune(),
  prod_degree = tune::tune(),
  prune_method = tune::tune()
) %>% 
  parsnip::set_engine("earth")
.tgr <- tune::tune_grid(
  mod_mars,
  # preprocessor = frm,
  preprocessor = rec,
  resamples = .roll,
  # iter = 2,
  # objective = "rmse",
  param_info = par_mars,
  grid = dials::grid_latin_hypercube(
    par_mars,
    size = 10
  ),
  control = tune::control_grid(
    verbose = TRUE,
    allow_par = TRUE,
    pkgs = "earth"
  )
)

```

By simply changing:
`num_terms = dials::num_terms(c(1,1))` to `num_terms = dials::num_terms(c(1L,1L))` 
it appears to resolve the issue. 

I think this could be fixed by changing [param_num_comp.R#L19](https://github.com/tidymodels/dials/blob/720cbfcde4d44a1a389c77859600d7d674808870/R/param_num_comp.R#L19) & [param_num_comp.R#L32](https://github.com/tidymodels/dials/blob/720cbfcde4d44a1a389c77859600d7d674808870/R/param_num_comp.R#L32) 
which currently read:
`range = range,`
to 
`range = vctrs::vec_cast.integer(range, "integer"),`

*Update 2020-07-15 09:05* I can't seem to replicate the fix by changing the range to integers in `num_terms` anymore. I'm not sure what changed, but this solution no longer seems to work.
*Update 2020-07-15 09:06* Removing `num_terms` altogether from the tuning does fix the issue, so `num_terms` is definitely involved in causing the error - though I'm not sure where.

Thanks!

**Comment by topepo** [comment]
I suspect that you had an older version of `dials`. There was no session info in the original issue. Can you provide one now?

**Comment by topepo** [comment]
Try with version 0.0.9 (on CRAN)

**Comment by yogat3ch** [comment]
Will do tomorrow and report the results!

**Comment by yogat3ch** [comment]
Everything checks out! Issue resolved! Thanks @topepo & @juliasilge !
