### ISSUE TITLE
Unknown Values and using update_role

### ISSUE THREAD

**Issue by Nilafhiosagam** [tidymodels/dials#134]
mtry() for example is dependant on data size

I don't know if this is currently possible, but would it be useful to reference a recipe so grid can be made of the number of predictors? For example my df may have 50 columns, but 5 might have an "ID" role

**Comment by juliasilge** [comment]
If you are using a parsnip model (i.e. not tune) you might [look into data descriptors](https://parsnip.tidymodels.org/reference/descriptors.html) such as `.cols()`. You can specify a model such as:

```r
library(parsnip)

rand_forest(mode = "classification", mtry = .cols() - 2)
```

There is not support for this in tune and dials currently.
