### ISSUE TITLE
Re-licensing dials 💥

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/dials#156]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/dials/graphs/contributors). 

@adanvr, @EmilHvitfeldt, @gabrielodom, @karawoo, @kmdupr33, would you permit us to re-license dials with the MIT license? If so, please comment "I agree" below.

* [x] [@adanvr](https://github.com/tidymodels/dials/commits?author=adanvr)  
* [x] [@EmilHvitfeldt](https://github.com/tidymodels/dials/commits?author=EmilHvitfeldt)  
* [x] [@gabrielodom](https://github.com/tidymodels/dials/commits?author=gabrielodom)  
* [x] [@karawoo](https://github.com/tidymodels/dials/commits?author=karawoo)  
* [x] [@kmdupr33](https://github.com/tidymodels/dials/commits?author=kmdupr33)

**Comment by karawoo** [comment]
I agree 🙂

**Comment by EmilHvitfeldt** [comment]
I agree! 👍

**Comment by adanvr** [comment]
I agree!

**Comment by gabrielodom** [comment]
I agree. Great job on the package!

**Comment by kmdupr33** [comment]
I agree!

**Comment by juliasilge** [comment]
Thanks so much, everyone! 🙌
