### ISSUE TITLE
Need dials parameter for `stop_iter`

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/dials#158]
In tidymodels/parsnip#437 @jrosell points out that although parsnip tries to [use a dials parameter for `stop_iter` in `boost_tree()`](https://github.com/tidymodels/parsnip/blob/110257f3c1566043239e6c08e6d16d81cb4b5116/R/boost_tree_data.R#L73), there isn't actually one.

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip

model_spec <- boost_tree(stop_iter = tune()) %>%
  set_mode("regression") %>%
  set_engine("xgboost")

parameters(model_spec)
#> Error: Problem with `mutate()` input `object`.
#> x Error when calling stop_iter(): Error : 'stop_iter' is not an exported object from 'namespace:dials'
#> 
#> ℹ Input `object` is `purrr::map(call_info, eval_call_info)`.
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jrosell** [comment]
Thanks @juliasilge!

**Comment by mbac** [comment]
Justa a heads-up. I installed `tidymodels\tidymodels` just today, and I got an earlier version of `dials`.

I used `remotes::install_github(‘tidymodels/dials’), force = T)` and I finally got the version with the bug squashed.
