### ISSUE TITLE
textrecipes tuning parameters

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/dials#16]
In accordance to https://github.com/EmilHvitfeldt/textrecipes/issues/14 here are my thoughts on what should be tunable.

`step_texthash`: `num_terms` integer.

`step_tf`: `weight` numeric.

`step_tokenfilter`: `max` numeric. `min` numeric. `max_tokens` integer.

Question.
Would something like `weight_scheme` in `step_tf` be tunable as it takes a couple of different (method as characters) values?

**Comment by topepo** [comment]
Could you change `min` and `max` to something like `min_occurance` or `min_times` or something more specific? 

> Would something like `weight_scheme` in `step_tf` be tunable as it takes a couple of different (method as characters) values?

Sure. We have qualitative parameters in other models too.

**Comment by EmilHvitfeldt** [comment]
> Could you change min and max to something like min_occurance or min_times or something more specific?

Done. Changed to *_times.

> Sure. We have qualitative parameters in other models too.

Then I have these additions.

`step_tf`: `weight_scheme` takes the following values: "binary", "raw count", "term frequency", "log normalization", "double normalization".

`step_tokenize`: `token` takes the following values: "characters", "character_shingle", "lines", "ngrams", "paragraphs", "ptb", "regex", "sentences", "skip_ngrams", "tweets", "words", "word_stems".

**Comment by EmilHvitfeldt** [comment]
Would a whole step be `dial`able?

**Comment by topepo** [comment]
I've thought about the issue of including a step or not. We could add an `eval_step` option that is logical and add a tuning parameter for it that way.

**Comment by EmilHvitfeldt** [comment]
That would be great!

**Comment by topepo** [comment]
Should `weight` be between `[0, 1]`?

**Comment by EmilHvitfeldt** [comment]
Mainly `weight` should be positive. But I think it is reasonable to bound it in `[0, 1]`.

**Comment by topepo** [comment]
Mind if I default `weight` to be on the log scale?

**Comment by EmilHvitfeldt** [comment]
That should be fine.

**Comment by topepo** [comment]
Take a look at [this commit](https://github.com/tidymodels/dials/commit/ea877efe888e96378a174c4a2850d7c6f2b29b7f) and let me know if the default ranges (or anything else) should be changed.

**Comment by EmilHvitfeldt** [comment]
Looks good.

**Comment by topepo** [comment]
Gak. I think that we need large numbers instead of `Inf`:

```r
> max_times
Maximum Token Frequency  (quantitative)
Range: [1, Inf]
> grid_random(max_times, size = 5)
 Show Traceback
 
 Rerun with Debug
 Error in min(unlist(object$range)):max(unlist(object$range)) : 
  result would be too long a vector 
```

What should we put in? We could do:

```r
> .Machine$integer.max
[1] 2147483647
> library(dials)
> max_times
Maximum Token Frequency  (quantitative)
Range: [1, 2147483647]
> grid_random(max_times, size = 5)
# A tibble: 5 x 1
   max_times
       <int>
1 1024987753
2 2080355927
3 1342632065
4   48813909
5   85432412
```

Maybe something smaller like `as.integer(10^5)`?

**Comment by topepo** [comment]
merged PR
