### ISSUE TITLE
revise `parameters.default` error message to point out class of `x`

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/dials#225]
The current source for `parameters.default` is:

https://github.com/tidymodels/dials/blob/252f8f61476815c1f2b33965f0f300d68de722cf/R/parameters.R#L14-L16

Would you be open to a PR that revises the error message here to include mention of `class(x)[1]`? Maybe something like:

```
Error:
! `parameters` objects cannot be created from objects of class `tune_results`.
```

I'm currently debugging some internals of stacks where the call to `parameters()` is pretty deep in the call stack, and imagine that some other common usages of `parameters()` may not be user-facing—some mention of what was being passed to where may have saved a round or two of `debugonce(...)`/`options(error = recover)`. :)

**Comment by hfrick** [comment]
that sounds like a good idea 👍
