### ISSUE TITLE
mtry_log?

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/dials#23]
Not `mtry_long` right? 🤔 

https://github.com/tidymodels/dials/blob/master/R/parameters.R#L51

From the docs:
"The latter uses a log transformation and is helpful when the data set has a large number of columns"

Does "long" refer to a large number of columns or is this a typo?

**Comment by DavisVaughan** [comment]
@topepo if you could confirm this is a typo, that'd be great

**Comment by topepo** [comment]
Yes, long is not a typo. I wanted to have a version of `mtry` that is more useful when there are thousands of predictors. `mtry_wide` might be a better name. 

Also, we might not even want to keep this since people could easily put this parameter on the log scale.

**Comment by DavisVaughan** [comment]
With the PR you can do `mtry(range = c(0L, unknown()), trans = log10_trans())` so yea we can probably remove it

**Comment by DavisVaughan** [comment]
Oooh if the PR is merged and we want to do this, then this could be a nice dev day example for soft deprecating things since we probably wouldn't want to remove it outright in the next version?
