### ISSUE TITLE
A small vignette on creating novel parameters

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/dials#25]
Even though it is mentioned [here](https://tidymodels.github.io/dials/articles/Basics.html#creating-novel-parameters), I think that a small vignette that functions as a walkthrough of creating new parameters would be useful. 

It could:

- Create a quantitative parameter using: `new_quant_param()`
- Create a qualitative character parameter using: `new_qual_param()`
- Maybe mention that you can also create logical qualitative parameters
- Talk about the different arguments to `new_quant_param()` and `new_qual_param()`, in particular, maybe use `trans` and `inclusive`
- Talk about using `unknown()` for unknown values
- Show how you immediately can use it with the other dials functions, and even use it in a grid with other parameters

Once the vignette was created, it would be appropriate to remove the section linked above.

Additionally, the `pkgdown` site would need to be updated, and a link to the vignette would need to be added to the `pkgdown` yaml navbar

**Comment by jonthegeek** [comment]
Working on this for tidy-dev-day, since I think I'll want to do this in [RBERT](github.com/jonathanbratt/RBERT)!

**Comment by topepo** [comment]
Added to `tidymodels.org` based on @jonthegeek's draft.
