### ISSUE TITLE
make S3 methods for grid functions that dispatch from model/recipe/workflow

### ISSUE THREAD

**Issue by topepo** [tidymodels/dials#335]
To eliminate a step of extracting the parameter set and for future-proofing for mixed grids (where we need to know about submodel parameters).

**Comment by hfrick** [comment]
So `grid_random.recipe()` or `grid_space_filling.workflow()`? Since we generally try to stick S3 methods for a class into the same package as the class itself, should we open issues for this on recipes/parsnip/workflows?
