### ISSUE TITLE
Eventually move varying() and varying_args() to dials

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/dials#40]
Currently importing parsnip in the `unique-id` branch just to get access to `varying_args()`. That function should eventually live in dials. Will need to:

* Move the parsnip `varying.R` file to dials
* Move the corresponding tests over too
* In dials, remove the parsnip import
* In parsnip, add a dials import
* In parsnip, add a dials remote so installs from github pull in the right thing
* In parsnip, re-export `varying()` and `varying_args()` (at least for 1 release) so we don't break anything
* In dials, export the currently un-exported parsnip function, `is_varying()` so parsnip can use it internally.

This should probably wait until the branches are all merged into master so we can use `Remotes: tidymodels/dials`

**Comment by topepo** [comment]
These (actually their replacements) are moving into `tune`
