### ISSUE TITLE
cross product of resamples and model specifications

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/dials#44]
would it be possible to just make a cross product of resamples and model specifications to be super explicit? like `crossing(rset_object, list_of_specifications)`? or is this going to be wildly memory inefficient? if so, could we make it memory efficient? i think it'd be way more intuitive

envisioned workflow:

```r

hp_grid <- grid_random(
  Cp,
  min_n %>% range_set(c(2, 20)),
  tree_depth,
  size = 10
)

spec_list <- merge(model, hp_grid)

library(rsample)

folds <- vfold_cv(iris, repeats = 10, v = 5)
folds

all_specs_all_folds <- crossing(folds, spec_list)
```

and then just `map` to `fit` everything all at once?

not sure where this should live. perhaps in the pipeline object package? cc @DavisVaughan @topepo

**Comment by alexpghayes** [comment]
Using `crossing()` on an `rset` appears to cost only in terms of the new data you add, not the resamples. Totally convinced this is a more intuitive way to present resampling!

``` r
library(rsample)
#> Warning: package 'rsample' was built under R version 3.5.2
#> Loading required package: tidyr
#> Warning: package 'tidyr' was built under R version 3.5.1
library(mlbench)
#> Warning: package 'mlbench' was built under R version 3.5.2
library(pryr)
#> Warning: package 'pryr' was built under R version 3.5.2

data(LetterRecognition)

object_size(LetterRecognition)
#> 2.64 MB

boots <- bootstraps(LetterRecognition, times = 50)
object_size(boots)
#> 6.69 MB

crossed <- crossing(boots, 1:1000)
crossed
#> # A tibble: 50,000 x 3
#>    splits             id          `1:1000`
#>    <list>             <chr>          <int>
#>  1 <split [20K/7.4K]> Bootstrap01        1
#>  2 <split [20K/7.4K]> Bootstrap01        2
#>  3 <split [20K/7.4K]> Bootstrap01        3
#>  4 <split [20K/7.4K]> Bootstrap01        4
#>  5 <split [20K/7.4K]> Bootstrap01        5
#>  6 <split [20K/7.4K]> Bootstrap01        6
#>  7 <split [20K/7.4K]> Bootstrap01        7
#>  8 <split [20K/7.4K]> Bootstrap01        8
#>  9 <split [20K/7.4K]> Bootstrap01        9
#> 10 <split [20K/7.4K]> Bootstrap01       10
#> # ... with 49,990 more rows

object_size(crossed)
#> 7.69 MB
```

<sup>Created on 2019-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by topepo** [comment]
Closing. 

We discourage the crossing/expanding of `rsample` objects in favor or keeping those static and creating list columns of results across the other variables. See the results of `tune` functions.
