### ISSUE TITLE
cost_complexity and cp not playing nicely

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/dials#45]
The `decision_tree` class has a parameter called `complexity_cost` but the corresponding `dials` object is called `Cp` and so I presume this breaks things somewhere. I assume the fix is to rename `Cp` to `cost_complexity`?

``` r
library(parsnip)
#> Warning: package 'parsnip' was built under R version 3.5.1
library(dials)
#> Loading required package: scales
#> Warning: package 'scales' was built under R version 3.5.1
#> 
#> Attaching package: 'dials'
#> The following object is masked from 'package:datasets':
#> 
#>     trees

model <- decision_tree()
grid <- grid_random(Cp)

merge(model, grid)
#> Random Forest Model Specification (unknown)
```

<sup>Created on 2019-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by zenggyu** [comment]
I encountered this issue, too. The work around is

```
model_spec <- decision_tree()
param_grid <- grid_random(Cp) %>% rename(cost_complexity = Cp)
merge(model, grid)
```

I think this is a little confusing. Why not just name the param object `cost_complexity` ?
