### ISSUE TITLE
Dense feature matrix for hyperparameter specification

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/dials#46]
Have been playing with `dials` recently and also reading [this about feature matrices](https://www.evanmiller.org/feature-matrix.html). I'm realizing I often work with models specification + hyperparameters in three different formats:

1. Flat tibble, with one column for the model specification (hyperparameters being `varying()`) and one column for each hyperparameter
2. Nested (packed?) tibble, with one column for the model specification (again with `varying()`) and a list-column of one-row tibbles. (i.e. a nested version of 1)
3. Tibble with a list-column (or just list) of model specifications with hyperparameters specified in the model specification object itself

It would be nice to have well-documented / named functions for going between any two of these formats. Hopefully this makes sense -- it not I can provide some code.

**Comment by topepo** [comment]
I'm going to call this out of scope until we have a pressing need to add it.
