### ISSUE TITLE
All parameters should have fully specified defaults

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/dials#49]
Even if the defaults are terrible, every parameter should have fully specified defaults. It's just too frustrating writing skeleton / starter code otherwise when you run into 

> Error: At least one parameter contains unknowns.

**Comment by topepo** [comment]
We have `finalize()` methods for these and `tune` will finalize them if left unknown. 

There is too much of a problem by having mandatory but bad defaults. For example, `mtry` is impossible to default. If you make the high end of the range small to accommodate most data sets, it is essentially close to 1 for very wide data sets.
