### ISSUE TITLE
grid_regular() and grid_random() should both accept size arguments

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/dials#52]
Having to remember to switch between `size` and `levels` is a pain. Users are probably thinking in terms of their computational budget, not the spacing of the grid, so the `levels` argument makes them do more work then they need / want to.

**Comment by topepo** [comment]
`train` uses the same argument for both grid search and random search. Since that has caused a lot of confusion, I deliberately made these argument names more descriptive (and different).
