### ISSUE TITLE
Rewrite "Working with parsnip" vignette

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/dials#69]
Is the rewrite of this vignette waiting for additional changes in the codebase, or just to get standardized with the changes in dials 0.0.3? I'm working through understanding how to connect them, so I can take on a revision of that vignette as part of understanding the changes if it's just a matter of applying the changes.

In any case, a vignette to understand how to connect dials and parsnip would be super helpful to actually use dials.

**Comment by jonthegeek** [comment]
Er, hmm. Is dials really usable with parsnip without tune::merge being available?

**Comment by ttzhou** [comment]
Seconded - some scripts I used for modeling now break because I used `merge.model_spec(model, dial_param_grid)`, and now it doesn't work (throws the usual base R merge error about not being a data frame).

**Comment by jonthegeek** [comment]
Nevermind! It looks like tune has this covered.
