### ISSUE TITLE
offset() name collision with stats::offset()

### ISSUE THREAD

**Issue by RoelVerbelen** [tidymodels/dials#75]
Given that the use of an offset is important in modelling context, it would be better to avoid the name clash of `dials::offset()` and `stats::offset()` leading to errors like these (when attaching tidymodels before modelling):

```r
library(dials) # or library(tidymodels)
data("Insurance", package = "MASS")
glm(Claims ~ District + Group + Age + offset(log(Holders)),
    data = Insurance, family = poisson)
Error: `range` must have an upper and lower bound. `Inf` and `unknown()` are acceptable values.
```

**Comment by topepo** [comment]
Yeah, we could call it `kernel_offset()`.
