### ISSUE TITLE
Not generating sampling values between 0 and 1 for sample size

### ISSUE THREAD

**Issue by temuulene** [tidymodels/dials#76]
### The problem
We want different proportions of sample size to expose when using sample size tuning for xgboost. But currently sampling from a range between 0 and 1 only gives us either 0 or 1. 

### Reproducible example
``` r
library(magrittr)
library(dials)
#> Loading required package: scales
#> 
#> Attaching package: 'dials'
#> The following object is masked from 'package:stats':
#> 
#>     offset

sample_size() %>% range_set(c(0, 1)) %>% value_sample(10)
#>  [1] 0 0 1 1 1 0 1 0 1 0
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by EmilHvitfeldt** [comment]
Do get sample proportions you should use `sample_prop()` instead of `sample_size()`

``` r
library(magrittr)
library(dials)
#> Loading required package: scales
#> 
#> Attaching package: 'dials'
#> The following object is masked from 'package:stats':
#> 
#>     offset

sample_prop() %>% range_set(c(0, 1)) %>% value_sample(10)
#>  [1] 0.69376990 0.91550858 0.70130150 0.03913977 0.25563324 0.88533639
#>  [7] 0.53029836 0.08411544 0.69032041 0.36662362
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by temuulene** [comment]
Got it. Thanks very much, Emil! Have a wonderful Thanksgiving!
