### ISSUE TITLE
rename margin and deprecate

### ISSUE THREAD

**Issue by topepo** [tidymodels/dials#85]
The dials parameter `margin()` has the same name as other R functions (including one in `ggplot2`). 

Let's make a copy called `svm_margin()` and add a warning when `margin()` is called that tells them that it is deprecated and will be removed in the next version (plus a test case for this similar to [this](https://github.com/tidymodels/recipes/blob/ff1552df370aeda6a15a4e349a8c5c5591a4b548/tests/testthat/test_basics.R#L116).

**Comment by gabrielodom** [comment]
Working on this with @gralgomez

**Comment by gabrielodom** [comment]
TO DO:
- Create a copy of `margin()` in `param_svm.R` named `svm_margin()`.
- Add a deprecation warning to `margin()`
- Add test for `svm_margin()` to `testthat/test_parameters.R`
- Update test for `margin()` in `testthat/test_parameters.R` to expect deprecation warning
- Add test for `margin()` in `testthat/test_deprecate.R` to check for deprecation warning

**Comment by DavisVaughan** [comment]
Closed by #91
