### ISSUE TITLE
new_quant_param finalize = NULL vs default = unknown

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/dials#90]
As far as I can tell in the code, most quant params are constructed with `default = unknown()` and `finalize = NULL`. Could this cause issues? I'm trying to wrap my head around exactly when it'd be possible for even a qual param to fall through to "care" about the default, but it seems off that most quant params could theoretically come out of tuning with `unknown()` still set (since `finalize.param` starts with `if (is.null(object$finalize)) return(object)`. Maybe that would never happen? To be honest, I'm not grasping when the `default` value would ever be used.

**Comment by topepo** [comment]
The default would be used when initializing some models. If the underlying function does not have a default, the parameter object can provide one. 

I don't think that this feature gets used anywhere but it is there.

**Comment by juliasilge** [comment]
Thanks for this discussion! 🙌
